config/routes.rb
SampleRealState::Application.routes.draw do
  devise_for :admins

  root 'products#index'
  resources :products do
    collection do
      post :import
      post :edit_multiple
    end
  end

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable
  
end

app/models/product.rb
class Product < ActiveRecord::Base
require 'csv'
 
  def self.import(file)
    CSV.foreach(file.path, headers: true, :encoding => 'ISO-8859-1') do |row|
  		title	= row[0]
  		titlelink	= row[1]
  		price	= row[2]
  		room	= row[3]
  		roomlink	= row[4]
  		area	= row[5]
  		arealink	= row[6]
  		person	= row[7]
  		personlink	= row[8]
  		date			= row[9]
      Product.create!(:title => title,:titlelink => titlelink, :price => price,
      	:room => room,	:roomlink => roomlink, :area => area, :arealink => arealink,
      	:person => person,:personlink => personlink,:date => date)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_action :authenticate_admin! , :only => [:edit, :update, :destroy]
	before_action :set_product, only: [:show, :edit, :update, :destroy]

	def index
    @products = Product.all.paginate(:page => params[:page], :per_page => 50)
  end

	def import
	  Product.import(params[:file])
	  redirect_to root_url, notice: "Products imported."
	end

	def edit
	end

	def show
		@product = Product.find(params[:id])
	end

	def new
	end

	def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render action: 'show', status: :created, location: @product }
      else
        format.html { render action: 'new' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end

  def edit_multiple
    @products = Product.find(params[:product_ids])
    if @products.map{|x| x.delete}
      redirect_to root_url, notice: 'Products was successfully deleted.'
    end
  end

	private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title,:titlelink,:price,:room,:roomlink,:area,:arealink,
      																:person,:personlink,:date)
    end

end

app/controllers/sessions_controller.rb
class Devise::SessionsController < DeviseController

  prepend_before_filter :require_no_authentication, :only => [ :new, :create ]
  prepend_before_filter :allow_params_authentication!, :only => :create
  prepend_before_filter { request.env["devise.skip_timeout"] = true }
  prepend_before_filter :verify_admin, only: [:destroy]
  skip_before_filter :verify_authenticity_token, only: [:destroy]


  # GET /resource/sign_in
  def new
    self.resource = resource_class.new(sign_in_params)
    clean_up_passwords(resource)
    respond_with(resource, serialize_options(resource))
  end

  # POST /resource/sign_in
  def create
    self.resource = warden.authenticate!(auth_options)
    set_flash_message(:notice, :signed_in) if is_navigational_format?
    sign_in(resource_name, resource)
    resource.exclude_root = 1 if resource.respond_to?(:exclude_root)
    resource.current_punchh_app = punchh_app if resource.respond_to?(:current_punchh_app) && punchh_app
    flash[:notice] = "succefully Login."
    respond_with resource, :location => after_sign_in_path_for(resource)
  end

  # DELETE /resource/sign_out
  def destroy
    redirect_path = after_sign_out_path_for(resource_name)
    signed_out = (Devise.sign_out_all_scopes ? sign_out : sign_out(resource_name))
    set_flash_message :notice, :signed_out if signed_out && is_navigational_format?

    # We actually need to hardcode this as Rails default responder doesn't
    # support returning empty response on GET request
    respond_to do |format|
      format.all { head :no_content }
      format.any(*navigational_formats) { redirect_to redirect_path }
    end
  end

  protected

  def sign_in_params
    devise_parameter_sanitizer.sanitize(:sign_in)
  end

  def resolve_layout
    [:mobile,:iframe].include?(request.format.to_sym) ? "application" : "new_layout"
  end

  def serialize_options(resource)
    methods = resource_class.authentication_keys.dup
    methods = methods.keys if methods.is_a?(Hash)
    methods << :password if resource.respond_to?(:password)
    { :methods => methods, :only => [:password] }
  end

  def auth_options
    { :scope => resource_name, :recall => "#{controller_path}#new" }
  end

  def verify_admin
    ## redirect to appropriate path
    redirect_to new_admin_session_path, notice: 'You have already signed out. Please sign in again.' and return unless admin_signed_in?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SampleRealState</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="row header" style="margin-bottom:20px;">
		<div class="container">
			<div class="col-md-5" >
			  <h4 style="padding-top:5px;">Office Space</h4>
			</div>
			<div class="col-md-6" >
			  <ul class="nav navbar-nav navbar-right">
          <li><a href="#">Buy</a></li>
          <li><a href="#">Sell</a></li>
          <li><a href="#">Rent</a></li>
          <li><a href="#">Advice</a></li>
          <li><a href="#">Find Agent</a></li>
          <% if current_admin.present? %>
			      <li class="dropdown">
			        <%= link_to("#{current_admin.email} <b class='caret'></b>".html_safe, "#", :class=> "dropdown-toggle", :'data-toggle' => "dropdown") %>
			        <ul class="dropdown-menu">
			          <li><%= link_to("<i class='icon-off'></i> Logout".html_safe, destroy_admin_session_path, :method => "delete", :data => {:confirm => "Are u sure want to logout?"}) %></li>
			        </ul>
			      </li>
			    <% else %>
			      <li class="dropdown " id="menuLogin" style="color:#000;">
			        <%= link_to("Login", new_admin_session_path, :class=> "dropdown-toggle ", :'data-toggle' => "dropdown") %>
			        <div class="dropdown-menu popup_login">
			          <%= form_for(:admin, url: admin_session_path, :authenticity_token => true, :class=>"form-horizontal") do |f| %>
			            <h3>Sign In</h3>
			              <%= f.text_field :email, required: false, placeholder: "email", label: false, autofocus: true, :class=>"input-large" %>
			              <%= f.text_field :password, type: :password, required: false, label: false, placeholder: "password", :class=>"input-large" %>
			              <div class="clearfix"></div>
			              <%#= f.text_field :remember_me, as: :boolean if devise_mapping.rememberable? %>
			              <div class="clearfix"></div>
			              <%= f.submit %>
			          <% end %>
			        </div>
			      </li>
			    <% end %>
        </ul>
			</div>
		<div class="col-md-1" ></div>
		</div>
	</div>
	<div class="container">
	<%= yield %>
	</div>
	 <div class="row footer">
	 	<div class="container">
	 		<span class="pull-right"><h6>© 2014 officespace.in. All rights reserved.</h6></span>
	 	</div>
	</div>
</body>
</html>

app/views/products/edit.html.erb
<div class="col-md-12" style="border-bottom:1px solid #ddd; margin-bottom:20px;">
</div>
<div class="container">
  <div class="col-md-11" style="border-bottom:1px solid #ddd; margin-bottom:20px;">
    <%= form_for(@product) do |f| %>
      <% if @product.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

          <ul>
          <% @product.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <%= f.label :title %><br>
        <%= f.text_field :title %>
      </div>
      <div class="field">
        <%= f.label :roomlink %><br>
        <%= f.text_field :titlelink %>
      </div>
      <div class="field">
        <%= f.label :price %><br>
        <%= f.text_field :price %>
      </div>
      <div class="field">
        <%= f.label :room %><br>
        <%= f.text_field :room %>
      </div>
      <div class="field">
        <%= f.label :roomlink %><br>
        <%= f.text_field :roomlink %>
      </div>
      <div class="field">
        <%= f.label :area %><br>
        <%= f.text_field :area %>
      </div>

      <div class="field">
        <%= f.label :arealink %><br>
        <%= f.text_field :arealink %>
      </div>
      <div class="field">
        <%= f.label :person %><br>
        <%= f.text_field :person %>
      </div>
      <div class="field">
        <%= f.label :personlink %><br>
        <%= f.text_field :personlink %>
      </div>
      <div class="field">
        <%= f.label :date %><br>
        <%= f.text_field :date %>
      </div>
      <div class="actions">
        <%= f.submit %>
      </div>
    <% end %>
  </div>
</div>

app/views/products/index.html.erb
<%= flash[:notice] %>

<% if current_admin.present? %>
	<h3>Import a CSV File</h3>
	<%= form_tag import_products_path, multipart: true do %>
	  <%= file_field_tag :file %>
	  <%= submit_tag "Import CSV" %>
	<% end %>
<% end %>
<div class="container">
	<div class="col-md-11" style="border-bottom:1px solid #ddd; margin-bottom:20px;">
		<%= form_tag edit_multiple_products_path do %>
		  <% if @products.present? %>
		    <table class="table table-hover">
		      <thead>
		        <tr>
		          <th>Project</th>
		          <th>Price</th>
		          <th>Room</th>
		          <th>Area</th>
		          <th>Person</th>
		          <th>Released</th>
		          <% if current_admin.present? %>
			          <th>Edit</th>
			          <th>Delete</th>
			          <th>Delete Multiple</th>
			        <% end %>
		        </tr>
		      </thead>
		      <tbody>
		        <% @products.each do |product| %>
		          <tr>
		            <% project = truncate(product.title, :length => 30, :separator => ' ') %>
		            <% area = truncate(product.area, :length => 20, :separator => ' ') %>
		            <% person = truncate(product.person, :length => 20, :separator => ' ') %>
		            <td><%= link_to project, product.titlelink, :target=> "blank" %></td>
		            <td><%= link_to product.price, product.titlelink, :target=> "blank" %></td>
		            <td><%= link_to product.room, product.roomlink, :target=> "blank" %></td>
		            <td><%= link_to area, product.arealink, :target=> "blank" %></td>
		            <td><%= link_to person, product.personlink, :target=> "blank" %></td>
		            <td><%= link_to product.date, product.titlelink, :target=> "blank" %></td>
			          <% if current_admin.present? %>
			            <td><%= link_to "Edit", edit_product_path(product) %></td>
			            <td><%= link_to "Destroy", product, :method => :delete, data: { confirm: 'Are you sure buddy?' } %></td>
			            <td><%= check_box_tag "product_ids[]", product.id %></td>
			          <% end %>
		          </tr>
		        <% end %>
		      </tbody>
		    </table>
		  <% end %>
			<%= submit_tag "Delete Select" if current_admin.present? %>
		<% end %>
	  <%= will_paginate @products, renderer: BootstrapPagination::Rails %>
	</div>
</div>

app/views/products/new.html.erb
<div class="col-md-12" style="border-bottom:1px solid #ddd; margin-bottom:20px;">
</div>
<div class="container">
  <div class="col-md-11" style="border-bottom:1px solid #ddd; margin-bottom:20px;">
    <%= form_for(Product.new, :url => { :action => "create" }, :html => {:class => 'form form-horizontal new_user'}) do |f| %>

      <div class="field">
        <%= f.label :title %><br>
        <%= f.text_field :title %>
      </div>
      <div class="field">
        <%= f.label :roomlink %><br>
        <%= f.text_field :titlelink %>
      </div>
      <div class="field">
        <%= f.label :price %><br>
        <%= f.text_field :price %>
      </div>
      <div class="field">
        <%= f.label :room %><br>
        <%= f.text_field :room %>
      </div>
      <div class="field">
        <%= f.label :roomlink %><br>
        <%= f.text_field :roomlink %>
      </div>
      <div class="field">
        <%= f.label :area %><br>
        <%= f.text_field :area %>
      </div>

      <div class="field">
        <%= f.label :arealink %><br>
        <%= f.text_field :arealink %>
      </div>
      <div class="field">
        <%= f.label :person %><br>
        <%= f.text_field :person %>
      </div>
      <div class="field">
        <%= f.label :personlink %><br>
        <%= f.text_field :personlink %>
      </div>
      <div class="field">
        <%= f.label :date %><br>
        <%= f.text_field :date %>
      </div>
      <div class="actions">
        <%= f.submit %>
      </div>
    <% end %>
  </div>
</div>

app/views/products/show.html.erb
<div class="col-md-12" style="border-bottom:1px solid #ddd; margin-bottom:20px;">
  <h2 style="padding-left:50px;"><img src="/realestate.png"></h2>
</div>
<div class="container">
	<div class="col-md-11" style="border-bottom:1px solid #ddd; margin-bottom:20px;">
	  <% if @product.present? %>

	    <table class="table table-hover">
	      <thead>
	        <tr>
	          <th>Project</th>
	          <th>Price</th>
	          <th>Room</th>
	          <th>Area</th>
	          <th>Person</th>
	          <th>Released</th>
	        </tr>
	      </thead>
	      <tbody>
          <tr>
            <% project = truncate(@product.title, :length => 30, :separator => ' ') %>
            <% area = truncate(@product.area, :length => 20, :separator => ' ') %>
            <% person = truncate(@product.person, :length => 20, :separator => ' ') %>
            <td><%= link_to project, @product.titlelink, :target=> "blank" %></td>
            <td><%= link_to @product.price, @product.titlelink, :target=> "blank" %></td>
            <td><%= link_to @product.room, @product.roomlink, :target=> "blank" %></td>
            <td><%= link_to area, @product.arealink, :target=> "blank" %></td>
            <td><%= link_to person, @product.personlink, :target=> "blank" %></td>
            <td><%= link_to @product.date, @product.titlelink, :target=> "blank" %></td>
          </tr>
	      </tbody>
	    </table>

	  <% end %>
	</div>
</div>